[package]
name = "doan_chu_iota"
version = "0.0.1"
edition = "2024"

[dependencies]
Iota = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "devnet" }

[addresses]
doan_chu_iota = "0x0"
